name: ci

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed "s/[^[:alnum:]]/./g)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uapf-space-fe:latest, ${{ secrets.DOCKERHUB_USERNAME }}/uapf-space-fe:${{ steps.vars.outputs.branch }}.${{ steps.vars.outputs.sha_short }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
